import './globals.scss';

import type { Metadata } from 'next';

import { dosis } from '@app/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={dosis.className}>{children}</body>
    </html>
  );
}
